[package]
name = "client"
version.workspace = true
edition.workspace = true

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
hex_grid = { path = "../hex_grid" }

bevy = { workspace = true }
hexx = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tungstenite = { workspace = true }
url = { workspace = true }

[features]
default = ["dev"]
dev = ["bevy/dynamic_linking"]  # Hot reload en dev